# Fetching the latest node image on alpine linux
FROM node:alpine AS development

# Declaring env
ENV NODE_ENV=development

# Setting up the work directory
WORKDIR /react-app

# Installing dependencies
COPY ./package*.json ./

RUN npm install

# Copying all the files in our project
COPY . .

# Exposing port
EXPOSE 5173

# Starting our application
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]